In [1]:
import zipfile
import pandas as pd
import os
import numpy as np

# Load multiple zip files, identifies csv and merge dataframes

In [2]:
# create function that identifies all zip files in a location a return a list
def get_zip_files(directory_path):
    zip_files = []
    for root, dirs, files in os.walk(directory_path):
        for file in files:
            if file.endswith(".zip"):
                zip_file_path = os.path.join(root, file)
                zip_files.append(zip_file_path)
    return zip_files

In [3]:
# create a list with all the zip files of the survey chapters, exclude one
zip_list = get_zip_files(r'E:\pobreza_2021\data\emicron\2021')
zip_list.pop(5)
zip_list

['E:\\pobreza_2021\\data\\emicron\\2021\\Factor_expansion_departamental.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_caracteristicas_del_micronegocio.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_costos_gastos_y_activos.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_emprendimiento.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_identificacion.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_personal_ocupado_(propietario).zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_sitio_ubicacion.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_TIC.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_ventas_ingresos.zip']

In [4]:
# create function to open zip files, open folders, identifies csv files, read it as dataframe and save it

def load_csv_from_zip(zip_file_path):
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        for filename in zip_ref.namelist():
            if filename.endswith('.csv'):
                with zip_ref.open(filename) as csv_file:
                    df = pd.read_csv(csv_file, sep = ';')
                    df.columns = [col.lower() for col in df.columns]
                    return {zip_file_path: df}
    return None

In [5]:
# use the previous function to iterate in all zip files, to store all dataframes in a dictionary
csv_dict = {}
for zip_file in zip_list:
    result = load_csv_from_zip(zip_file)
    if result is not None:
        csv_dict.update(result)

# verify that the disctionaty ir fine

In [6]:
# Print the keys (zip file names) in the dictionary
print(csv_dict.keys())

# Print the values (dataframes) in the dictionary
print(csv_dict.values())

dict_keys(['E:\\pobreza_2021\\data\\emicron\\2021\\Factor_expansion_departamental.zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_caracteristicas_del_micronegocio.zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_costos_gastos_y_activos.zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_emprendimiento.zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_identificacion.zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_personal_ocupado.zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_personal_ocupado_(propietario).zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_sitio_ubicacion.zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_TIC.zip', 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_ventas_ingresos.zip'])
dict_values([       directorio  secuencia_encuesta  secuencia_p  fex_micro_dpto
0         5431912                   3            1      416.083305
1         5536831                   1            1      458.272472
2         5431864                   1            1      358.601892
3         5536858                   1            1      423.391278
4         5536808                   1            1      392.216919
...           ...                 ...          ...             ...
77151     5337681                   1            1        4.371001
77152     5337680                   1            1        4.874401
77153     5337677                   2            1        4.398226
77154     5337677                   1            1        4.398226
77155     5337678                   1            1        4.611550

[77156 rows x 4 columns],        directorio  secuencia_p  secuencia_encuesta  p1633  p986  p640  p4000  \
0         5299787            1                   1      2   NaN     3    NaN
1         5299791            1                   1      1   2.0     3    NaN
2         5299798            1                   1      2   NaN     5    3.0
3         5299801            1                   1      2   NaN     5    1.0
4         5299801            1                   2      2   NaN     5    1.0
...           ...          ...                 ...    ...   ...   ...    ...
77151     6036337            1                   1      2   NaN     5    1.0
77152     6036337            1                   2      2   NaN     5    1.0
77153     6036340            1                   1      2   NaN     5    1.0
77154     6036346            1                   1      2   NaN     5    1.0
77155     6036351            1                   1      2   NaN     5    1.0

       p1055  p1056  p661  p1057  p4004  p2991  p2992  p2993  clase_te  \
0          2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1
1          2    NaN   NaN    2.0    NaN    9.0    3.0    9.0         1
2          2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1
3          2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1
4          2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1
...      ...    ...   ...    ...    ...    ...    ...    ...       ...
77151      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1
77152      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1
77153      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1
77154      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1
77155      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1

       cod_depto  area      f_exp
0             68  68.0  65.643425
1             68  68.0  65.643425
2             54  54.0  36.606637
3             68  68.0  55.687148
4             68  68.0  55.687148
...          ...   ...        ...
77151         27  27.0   7.720844
77152         27  27.0   7.720844
77153         27  27.0   5.986418
77154         27  27.0   3.554411
77155         27  27.0   6.961748

[77156 rows x 19 columns],        directorio  secuencia_p  secuencia_encuesta   p3056_a    p3056_b  \
0         5299787            1                   1       NaN  2000000.0
1         5299791            1                   1  200000.0        NaN
2         5299798            1                   1       NaN        NaN
3         5299801            1                   1       NaN        NaN
4         5299801            1                   2       NaN        NaN
...           ...          ...                 ...       ...        ...
77151     6036337            1                   1   50000.0        NaN
77152     6036337            1                   2       NaN    20000.0
77153     6036340            1                   1       NaN   300000.0
77154     6036346            1                   1  200000.0        NaN
77155     6036351            1                   1       NaN   300000.0

       p3056_c  p3056_d  p3056_e    p3057_a     p3057_b  ...  p3018_f  \
0          NaN      NaN      NaN        NaN  20000000.0  ...      NaN
1          NaN      NaN      NaN  2200000.0         NaN  ...      NaN
2          NaN      NaN      0.0        NaN         NaN  ...      NaN
3          NaN      NaN  40000.0        NaN         NaN  ...      NaN
4          0.0      NaN      NaN        NaN         NaN  ...      NaN
...        ...      ...      ...        ...         ...  ...      ...
77151      NaN      NaN      NaN   200000.0         NaN  ...      NaN
77152      NaN      NaN      NaN        NaN    300000.0  ...      NaN
77153      NaN      NaN      NaN        NaN    830000.0  ...      NaN
77154      NaN      NaN      NaN  4075086.0         NaN  ...      NaN
77155      NaN      NaN      NaN        NaN   1700000.0  ...      NaN

           p3019  costos_mes_anterior  costos_anio_anterior  gastos_mes  \
0       500000.0              2000000            20000000.0      240000
1      8000000.0               200000             2200000.0      110000
2            0.0                    0              800000.0           0
3      1500000.0                40000              400000.0       30000
4        50000.0                    0              500000.0       23626
...          ...                  ...                   ...         ...
77151  1800000.0                50000              200000.0       30000
77152  3000000.0                20000              300000.0       60000
77153  2000000.0               300000              830000.0           0
77154  1000000.0               200000             4075086.0           0
77155        0.0               300000             1700000.0      234767

       consumo_intermedio  clase_te  cod_depto  area      f_exp
0                 2240000         1         68  68.0  65.643425
1                  310000         1         68  68.0  65.643425
2                       0         1         54  54.0  36.606637
3                   70000         1         68  68.0  55.687148
4                   23626         1         68  68.0  55.687148
...                   ...       ...        ...   ...        ...
77151               80000         1         27  27.0   7.720844
77152               80000         1         27  27.0   7.720844
77153              300000         1         27  27.0   5.986418
77154              200000         1         27  27.0   3.554411
77155              534767         1         27  27.0   6.961748

[77156 rows x 47 columns],        directorio  secuencia_p  secuencia_encuesta  p3050  p3051  p639  p3052  \
0         5299787            1                   1      2      1     1    1.0
1         5299791            1                   1      1      2     4    1.0
2         5299798            1                   1      1      1     4    1.0
3         5299801            1                   1      1      4     5    1.0
4         5299801            1                   2      3      7     2    1.0
...           ...          ...                 ...    ...    ...   ...    ...
77151     6036337            1                   1      1      1     3    6.0
77152     6036337            1                   2      1      1     3    6.0
77153     6036340            1                   1      1      2     3    1.0
77154     6036346            1                   1      2      1     5    1.0
77155     6036351            1                   1      1      4     5    6.0

       clase_te  cod_depto  area      f_exp
0             1         68  68.0  65.643425
1             1         68  68.0  65.643425
2             1         54  54.0  36.606637
3             1         68  68.0  55.687148
4             1         68  68.0  55.687148
...         ...        ...   ...        ...
77151         1         27  27.0   7.720844
77152         1         27  27.0   7.720844
77153         1         27  27.0   5.986418
77154         1         27  27.0   3.554411
77155         1         27  27.0   6.961748

[77156 rows x 11 columns],        directorio  secuencia_p  secuencia_encuesta  cod_depto  area  clase_te  \
0         5299787            1                   1         68  68.0         1
1         5299791            1                   1         68  68.0         1
2         5299798            1                   1         54  54.0         1
3         5299801            1                   1         68  68.0         1
4         5299801            1                   2         68  68.0         1
...           ...          ...                 ...        ...   ...       ...
77151     6036337            1                   1         27  27.0         1
77152     6036337            1                   2         27  27.0         1
77153     6036340            1                   1         27  27.0         1
77154     6036346            1                   1         27  27.0         1
77155     6036351            1                   1         27  27.0         1

       p35  p241    mes_ref  p3031  p3032_1  p3032_2  p3032_3  p3033  p3034  \
0        1    27      ENERO      2      NaN      NaN      NaN      2     11
1        2    54      ENERO      2      NaN      NaN      NaN      2     60
2        2    49      ENERO      2      NaN      NaN      NaN      2     96
3        1    35      ENERO      2      NaN      NaN      NaN      2    180
4        2    34      ENERO      2      NaN      NaN      NaN      2     24
...    ...   ...        ...    ...      ...      ...      ...    ...    ...
77151    2    66  DICIEMBRE      2      NaN      NaN      NaN      2     47
77152    1    63  DICIEMBRE      2      NaN      NaN      NaN      2     54
77153    1    53  DICIEMBRE      2      NaN      NaN      NaN      2    144
77154    2    56  DICIEMBRE      1      0.0      0.0      1.0      2    300
77155    2    35  DICIEMBRE      2      NaN      NaN      NaN      2    145

       p3035  p3000  grupos4  grupos12      f_exp
0          2      2        4         8  65.643425
1          2      2        3         5  65.643425
2          2      2        3         5  36.606637
3          2      2        4        10  55.687148
4          2      2        2         3  55.687148
...      ...    ...      ...       ...        ...
77151      2      2        3         5   7.720844
77152      2      2        4        12   7.720844
77153      2      2        4        12   5.986418
77154      2      2        3         5   3.554411
77155      2      2        4        12   6.961748

[77156 rows x 20 columns],        directorio  secuencia_ph  secuencia_p  secuencia_encuesta  tipo  p3077  \
0         5299851             1            1                   2     1    1.0
1         5299851             1            1                   1     1    1.0
2         5299900             1            1                   1     3    NaN
3         5299900             1            1                   1     1    2.0
4         5299900             1            1                   2     1    2.0
...           ...           ...          ...                 ...   ...    ...
22429     6036007             1            1                   1     1    2.0
22430     6036007             1            1                   2     1    2.0
22431     6036007             1            1                   3     1    2.0
22432     6036007             1            1                   4     1    2.0
22433     6036346             1            1                   1     3    NaN

       p3078      p3079  p3080     p3081  p3082     p3083  p3084  p2990  \
0          2   400000.0      2       NaN    2.0       NaN      2      2
1          2   400000.0      2       NaN    2.0       NaN      2      2
2          2        NaN      2       NaN    NaN       NaN      2      2
3          1  1200000.0      1  248000.0    2.0       NaN      2      2
4          1  1200000.0      1  248000.0    2.0       NaN      2      2
...      ...        ...    ...       ...    ...       ...    ...    ...
22429      2   908526.0      1  250000.0    1.0  198348.0      1      1
22430      2   908526.0      1  250000.0    1.0  198348.0      1      1
22431      1   908526.0      2       NaN    2.0       NaN      2      2
22432      1   908526.0      2       NaN    2.0       NaN      2      2
22433      1        NaN      2       NaN    NaN       NaN      2      2

       p3085  p3099  clase_te  cod_depto  area      f_exp
0         36     24         1         50  50.0  20.498500
1         36     29         1         50  50.0  20.498500
2        120     48         1         41  41.0   8.139682
3          3     33         1         41  41.0   8.139682
4          3     42         1         41  41.0   8.139682
...      ...    ...       ...        ...   ...        ...
22429     48     27         1         19  19.0  15.793466
22430     24     56         1         19  19.0  15.793466
22431     48     47         1         19  19.0  15.793466
22432     48     33         1         19  19.0  15.793466
22433    300     65         1         27  27.0   3.554411

[22434 rows x 20 columns],        directorio  secuencia_p  secuencia_encuesta  p3088     p3089  p3090  \
0         5299787            1                   1      1  300000.0      1
1         5299791            1                   1      2       NaN      2
2         5299798            1                   1      2       NaN      2
3         5299801            1                   1      2       NaN      2
4         5299801            1                   2      2       NaN      2
...           ...          ...                 ...    ...       ...    ...
77151     6036337            1                   1      2       NaN      2
77152     6036337            1                   2      2       NaN      2
77153     6036340            1                   1      2       NaN      2
77154     6036346            1                   1      2       NaN      2
77155     6036351            1                   1      2       NaN      2

       p2989  p3091  sueldos  prestaciones  remuneracion_total  clase_te  \
0          2      1      NaN        300000              300000         1
1          2      1      NaN             0                   0         1
2          2      1      NaN             0                   0         1
3          2      1      NaN             0                   0         1
4          2      1      NaN             0                   0         1
...      ...    ...      ...           ...                 ...       ...
77151      2      1      NaN             0                   0         1
77152      2      1      NaN             0                   0         1
77153      2      1      NaN             0                   0         1
77154      2      3      0.0             0                   0         1
77155      2      1      NaN             0                   0         1

       cod_depto  area      f_exp
0             68  68.0  65.643425
1             68  68.0  65.643425
2             54  54.0  36.606637
3             68  68.0  55.687148
4             68  68.0  55.687148
...          ...   ...        ...
77151         27  27.0   7.720844
77152         27  27.0   7.720844
77153         27  27.0   5.986418
77154         27  27.0   3.554411
77155         27  27.0   6.961748

[77156 rows x 15 columns],        directorio  secuencia_p  secuencia_encuesta  p3053  p3095  p3096  \
0         5299787            1                   1      1    2.0    NaN
1         5299791            1                   1      1    1.0    NaN
2         5299798            1                   1      3    NaN    NaN
3         5299801            1                   1      3    NaN    NaN
4         5299801            1                   2      1    2.0    NaN
...           ...          ...                 ...    ...    ...    ...
77151     6036337            1                   1      1    2.0    NaN
77152     6036337            1                   2      4    NaN    NaN
77153     6036340            1                   1      1    1.0    NaN
77154     6036346            1                   1      4    NaN    NaN
77155     6036351            1                   1      1    2.0    NaN

       p3097  p3098  p3054  p3055  p469  clase_te  cod_depto  area      f_exp
0        NaN    NaN    1.0    3.0   2.0         1         68  68.0  65.643425
1        NaN    NaN    1.0    1.0   1.0         1         68  68.0  65.643425
2        1.0    NaN    NaN    NaN   NaN         1         54  54.0  36.606637
3        1.0    NaN    NaN    NaN   NaN         1         68  68.0  55.687148
4        NaN    NaN    1.0    3.0   2.0         1         68  68.0  55.687148
...      ...    ...    ...    ...   ...       ...        ...   ...        ...
77151    NaN    NaN    1.0    1.0   1.0         1         27  27.0   7.720844
77152    NaN    1.0    NaN    NaN   NaN         1         27  27.0   7.720844
77153    NaN    NaN    1.0    1.0   1.0         1         27  27.0   5.986418
77154    NaN    1.0    NaN    NaN   NaN         1         27  27.0   3.554411
77155    NaN    NaN   99.0    1.0   2.0         1         27  27.0   6.961748

[77156 rows x 15 columns],        directorio  secuencia_p  secuencia_encuesta  p4001  p1087  p1088  p977  \
0         5299787            1                   1      2    NaN    NaN   NaN
1         5299791            1                   1      1    1.0    0.0   0.0
2         5299798            1                   1      2    NaN    NaN   NaN
3         5299801            1                   1      1    0.0    1.0   0.0
4         5299801            1                   2      2    NaN    NaN   NaN
...           ...          ...                 ...    ...    ...    ...   ...
77151     6036337            1                   1      2    NaN    NaN   NaN
77152     6036337            1                   2      2    NaN    NaN   NaN
77153     6036340            1                   1      2    NaN    NaN   NaN
77154     6036346            1                   1      2    NaN    NaN   NaN
77155     6036351            1                   1      2    NaN    NaN   NaN

       p976  p978  p979  ...  p1006_8  p1006_9  p1006_10  p1006_11  p1006_12  \
0         1   1.0   0.0  ...      2.0      2.0       2.0       2.0       2.0
1         2   NaN   NaN  ...      1.0      2.0       2.0       2.0       2.0
2         1   1.0   0.0  ...      2.0      2.0       2.0       2.0       2.0
3         1   1.0   0.0  ...      2.0      2.0       2.0       2.0       1.0
4         1   1.0   0.0  ...      2.0      2.0       2.0       2.0       1.0
...     ...   ...   ...  ...      ...      ...       ...       ...       ...
77151     2   NaN   NaN  ...      NaN      NaN       NaN       NaN       NaN
77152     2   NaN   NaN  ...      NaN      NaN       NaN       NaN       NaN
77153     2   NaN   NaN  ...      NaN      NaN       NaN       NaN       NaN
77154     2   NaN   NaN  ...      NaN      NaN       NaN       NaN       NaN
77155     1   1.0   0.0  ...      1.0      1.0       1.0       2.0       2.0

       p1006_13  clase_te  cod_depto  area      f_exp
0           1.0         1         68  68.0  65.643425
1           1.0         1         68  68.0  65.643425
2           1.0         1         54  54.0  36.606637
3           1.0         1         68  68.0  55.687148
4           1.0         1         68  68.0  55.687148
...         ...       ...        ...   ...        ...

In [7]:
# Iterate over the items in the dictionary
for zip_file_name, df in csv_dict.items():
    print(f'Dataframe for {zip_file_name}:')
    print(df.head())

Dataframe for E:\pobreza_2021\data\emicron\2021\Factor_expansion_departamental.zip:
   directorio  secuencia_encuesta  secuencia_p  fex_micro_dpto
0     5431912                   3            1      416.083305
1     5536831                   1            1      458.272472
2     5431864                   1            1      358.601892
3     5536858                   1            1      423.391278
4     5536808                   1            1      392.216919
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_caracteristicas_del_micronegocio.zip:
   directorio  secuencia_p  secuencia_encuesta  p1633  p986  p640  p4000  \
0     5299787            1                   1      2   NaN     3    NaN
1     5299791            1                   1      1   2.0     3    NaN
2     5299798            1                   1      2   NaN     5    3.0
3     5299801            1                   1      2   NaN     5    1.0
4     5299801            1                   2      2   NaN     5    1.0

   p1055  p1056  p661  p1057  p4004  p2991  p2992  p2993  clase_te  cod_depto  \
0      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1         68
1      2    NaN   NaN    2.0    NaN    9.0    3.0    9.0         1         68
2      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1         54
3      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1         68
4      2    NaN   NaN    2.0    NaN    NaN    NaN    NaN         1         68

   area      f_exp
0  68.0  65.643425
1  68.0  65.643425
2  54.0  36.606637
3  68.0  55.687148
4  68.0  55.687148
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_costos_gastos_y_activos.zip:
   directorio  secuencia_p  secuencia_encuesta   p3056_a    p3056_b  p3056_c  \
0     5299787            1                   1       NaN  2000000.0      NaN
1     5299791            1                   1  200000.0        NaN      NaN
2     5299798            1                   1       NaN        NaN      NaN
3     5299801            1                   1       NaN        NaN      NaN
4     5299801            1                   2       NaN        NaN      0.0

   p3056_d  p3056_e    p3057_a     p3057_b  ...  p3018_f      p3019  \
0      NaN      NaN        NaN  20000000.0  ...      NaN   500000.0
1      NaN      NaN  2200000.0         NaN  ...      NaN  8000000.0
2      NaN      0.0        NaN         NaN  ...      NaN        0.0
3      NaN  40000.0        NaN         NaN  ...      NaN  1500000.0
4      NaN      NaN        NaN         NaN  ...      NaN    50000.0

   costos_mes_anterior  costos_anio_anterior  gastos_mes  consumo_intermedio  \
0              2000000            20000000.0      240000             2240000
1               200000             2200000.0      110000              310000
2                    0              800000.0           0                   0
3                40000              400000.0       30000               70000
4                    0              500000.0       23626               23626

   clase_te  cod_depto  area      f_exp
0         1         68  68.0  65.643425
1         1         68  68.0  65.643425
2         1         54  54.0  36.606637
3         1         68  68.0  55.687148
4         1         68  68.0  55.687148

[5 rows x 47 columns]
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_emprendimiento.zip:
   directorio  secuencia_p  secuencia_encuesta  p3050  p3051  p639  p3052  \
0     5299787            1                   1      2      1     1    1.0
1     5299791            1                   1      1      2     4    1.0
2     5299798            1                   1      1      1     4    1.0
3     5299801            1                   1      1      4     5    1.0
4     5299801            1                   2      3      7     2    1.0

   clase_te  cod_depto  area      f_exp
0         1         68  68.0  65.643425
1         1         68  68.0  65.643425
2         1         54  54.0  36.606637
3         1         68  68.0  55.687148
4         1         68  68.0  55.687148
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_identificacion.zip:
   directorio  secuencia_p  secuencia_encuesta  cod_depto  area  clase_te  \
0     5299787            1                   1         68  68.0         1
1     5299791            1                   1         68  68.0         1
2     5299798            1                   1         54  54.0         1
3     5299801            1                   1         68  68.0         1
4     5299801            1                   2         68  68.0         1

   p35  p241 mes_ref  p3031  p3032_1  p3032_2  p3032_3  p3033  p3034  p3035  \
0    1    27   ENERO      2      NaN      NaN      NaN      2     11      2
1    2    54   ENERO      2      NaN      NaN      NaN      2     60      2
2    2    49   ENERO      2      NaN      NaN      NaN      2     96      2
3    1    35   ENERO      2      NaN      NaN      NaN      2    180      2
4    2    34   ENERO      2      NaN      NaN      NaN      2     24      2

   p3000  grupos4  grupos12      f_exp
0      2        4         8  65.643425
1      2        3         5  65.643425
2      2        3         5  36.606637
3      2        4        10  55.687148
4      2        2         3  55.687148
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_personal_ocupado.zip:
   directorio  secuencia_ph  secuencia_p  secuencia_encuesta  tipo  p3077  \
0     5299851             1            1                   2     1    1.0
1     5299851             1            1                   1     1    1.0
2     5299900             1            1                   1     3    NaN
3     5299900             1            1                   1     1    2.0
4     5299900             1            1                   2     1    2.0

   p3078      p3079  p3080     p3081  p3082  p3083  p3084  p2990  p3085  \
0      2   400000.0      2       NaN    2.0    NaN      2      2     36
1      2   400000.0      2       NaN    2.0    NaN      2      2     36
2      2        NaN      2       NaN    NaN    NaN      2      2    120
3      1  1200000.0      1  248000.0    2.0    NaN      2      2      3
4      1  1200000.0      1  248000.0    2.0    NaN      2      2      3

   p3099  clase_te  cod_depto  area      f_exp
0     24         1         50  50.0  20.498500
1     29         1         50  50.0  20.498500
2     48         1         41  41.0   8.139682
3     33         1         41  41.0   8.139682
4     42         1         41  41.0   8.139682
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_personal_ocupado_(propietario).zip:
   directorio  secuencia_p  secuencia_encuesta  p3088     p3089  p3090  p2989  \
0     5299787            1                   1      1  300000.0      1      2
1     5299791            1                   1      2       NaN      2      2
2     5299798            1                   1      2       NaN      2      2
3     5299801            1                   1      2       NaN      2      2
4     5299801            1                   2      2       NaN      2      2

   p3091  sueldos  prestaciones  remuneracion_total  clase_te  cod_depto  \
0      1      NaN        300000              300000         1         68
1      1      NaN             0                   0         1         68
2      1      NaN             0                   0         1         54
3      1      NaN             0                   0         1         68
4      1      NaN             0                   0         1         68

   area      f_exp
0  68.0  65.643425
1  68.0  65.643425
2  54.0  36.606637
3  68.0  55.687148
4  68.0  55.687148
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip:
   directorio  secuencia_p  secuencia_encuesta  p3053  p3095  p3096  p3097  \
0     5299787            1                   1      1    2.0    NaN    NaN
1     5299791            1                   1      1    1.0    NaN    NaN
2     5299798            1                   1      3    NaN    NaN    1.0
3     5299801            1                   1      3    NaN    NaN    1.0
4     5299801            1                   2      1    2.0    NaN    NaN

   p3098  p3054  p3055  p469  clase_te  cod_depto  area      f_exp
0    NaN    1.0    3.0   2.0         1         68  68.0  65.643425
1    NaN    1.0    1.0   1.0         1         68  68.0  65.643425
2    NaN    NaN    NaN   NaN         1         54  54.0  36.606637
3    NaN    NaN    NaN   NaN         1         68  68.0  55.687148
4    NaN    1.0    3.0   2.0         1         68  68.0  55.687148
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_TIC.zip:
   directorio  secuencia_p  secuencia_encuesta  p4001  p1087  p1088  p977  \
0     5299787            1                   1      2    NaN    NaN   NaN
1     5299791            1                   1      1    1.0    0.0   0.0
2     5299798            1                   1      2    NaN    NaN   NaN
3     5299801            1                   1      1    0.0    1.0   0.0
4     5299801            1                   2      2    NaN    NaN   NaN

   p976  p978  p979  ...  p1006_8  p1006_9  p1006_10  p1006_11  p1006_12  \
0     1   1.0   0.0  ...      2.0      2.0       2.0       2.0       2.0
1     2   NaN   NaN  ...      1.0      2.0       2.0       2.0       2.0
2     1   1.0   0.0  ...      2.0      2.0       2.0       2.0       2.0
3     1   1.0   0.0  ...      2.0      2.0       2.0       2.0       1.0
4     1   1.0   0.0  ...      2.0      2.0       2.0       2.0       1.0

   p1006_13  clase_te  cod_depto  area      f_exp
0       1.0         1         68  68.0  65.643425
1       1.0         1         68  68.0  65.643425
2       1.0         1         54  54.0  36.606637
3       1.0         1         68  68.0  55.687148
4       1.0         1         68  68.0  55.687148

[5 rows x 35 columns]
Dataframe for E:\pobreza_2021\data\emicron\2021\Modulo_ventas_ingresos.zip:
   directorio  secuencia_p  secuencia_encuesta     p3057  p3058  p3059  p3060  \
0     5299787            1                   1       NaN    NaN    NaN    NaN
1     5299791            1                   1       NaN    NaN    NaN    NaN
2     5299798            1                   1       NaN    NaN    NaN    NaN
3     5299801            1                   1       NaN    NaN    NaN    NaN
4     5299801            1                   2  150000.0    0.0    0.0    0.0

       p3061  p3062  p4002  ...    p3072  ventas_mes_anterior  \
0        NaN    NaN    NaN  ...  1000000              3500000
1  1200000.0    0.0    0.0  ...  1000000              1200000
2        NaN    NaN    NaN  ...    80000                    0
3        NaN    NaN    NaN  ...    50000               100000
4        NaN    NaN    NaN  ...   150000               150000

   ventas_mes_anio_anterior  ventas_anio_anterior  valor_agregado  \
0                       NaN            35000000.0         1260000
1                 1150000.0            14000000.0          890000
2                  300000.0             1200000.0               0
3                  400000.0             1400000.0           30000
4                  200000.0             2500000.0          126374

   ingreso_mixto  clase_te  cod_depto  area      f_exp
0         960000         1         68  68.0  65.643425
1         890000         1         68  68.0  65.643425
2              0         1         54  54.0  36.606637
3          30000         1         68  68.0  55.687148
4         126374         1         68  68.0  55.687148

[5 rows x 72 columns]

In [17]:
print(csv_dict['E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_identificacion.zip'].shape)
#csv_dict.items()

(77156, 20)

In [6]:
for df in csv_dict.keys():
    print(df)
    print(csv_dict[df].shape)

E:\pobreza_2021\data\emicron\2021\Factor_expansion_departamental.zip
(77156, 4)
E:\pobreza_2021\data\emicron\2021\Modulo_caracteristicas_del_micronegocio.zip
(77156, 19)
E:\pobreza_2021\data\emicron\2021\Modulo_costos_gastos_y_activos.zip
(77156, 47)
E:\pobreza_2021\data\emicron\2021\Modulo_emprendimiento.zip
(77156, 11)
E:\pobreza_2021\data\emicron\2021\Modulo_identificacion.zip
(77156, 20)
E:\pobreza_2021\data\emicron\2021\Modulo_personal_ocupado_(propietario).zip
(77156, 15)
E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip
(77156, 15)
E:\pobreza_2021\data\emicron\2021\Modulo_TIC.zip
(77156, 35)
E:\pobreza_2021\data\emicron\2021\Modulo_ventas_ingresos.zip
(77156, 72)

In [7]:
for zip_file_name, df in csv_dict.items():
    print(f'Columns name for {zip_file_name}:')
    print(df.columns)

Columns name for E:\pobreza_2021\data\emicron\2021\Factor_expansion_departamental.zip:
Index(['directorio', 'secuencia_encuesta', 'secuencia_p', 'fex_micro_dpto'], dtype='object')
Columns name for E:\pobreza_2021\data\emicron\2021\Modulo_caracteristicas_del_micronegocio.zip:
Index(['directorio', 'secuencia_p', 'secuencia_encuesta', 'p1633', 'p986',
       'p640', 'p4000', 'p1055', 'p1056', 'p661', 'p1057', 'p4004', 'p2991',
       'p2992', 'p2993', 'clase_te', 'cod_depto', 'area', 'f_exp'],
      dtype='object')
Columns name for E:\pobreza_2021\data\emicron\2021\Modulo_costos_gastos_y_activos.zip:
Index(['directorio', 'secuencia_p', 'secuencia_encuesta', 'p3056_a', 'p3056_b',
       'p3056_c', 'p3056_d', 'p3056_e', 'p3057_a', 'p3057_b', 'p3057_c',
       'p3057_d', 'p3057_e', 'p3017_a', 'p3017_b', 'p3017_c', 'p3017_d',
       'p3017_e', 'p3017_f', 'p3017_g', 'p3017_h', 'p3017_k', 'p3017_i',
       'p3017_j', 'p3017_l', 'p3018_1', 'p3018_2', 'p3018_3', 'p3018_4',
       'p3018_5', 'p3018_6', 'p3018_7', 'p3018_a', 'p3018_b', 'p3018_c',
       'p3018_d', 'p3018_e', 'p3018_f', 'p3019', 'costos_mes_anterior',
       'costos_anio_anterior', 'gastos_mes', 'consumo_intermedio', 'clase_te',
       'cod_depto', 'area', 'f_exp'],
      dtype='object')
Columns name for E:\pobreza_2021\data\emicron\2021\Modulo_emprendimiento.zip:
Index(['directorio', 'secuencia_p', 'secuencia_encuesta', 'p3050', 'p3051',
       'p639', 'p3052', 'clase_te', 'cod_depto', 'area', 'f_exp'],
      dtype='object')
Columns name for E:\pobreza_2021\data\emicron\2021\Modulo_identificacion.zip:
Index(['directorio', 'secuencia_p', 'secuencia_encuesta', 'cod_depto', 'area',
       'clase_te', 'p35', 'p241', 'mes_ref', 'p3031', 'p3032_1', 'p3032_2',
       'p3032_3', 'p3033', 'p3034', 'p3035', 'p3000', 'grupos4', 'grupos12',
       'f_exp'],
      dtype='object')
Columns name for E:\pobreza_2021\data\emicron\2021\Modulo_personal_ocupado_(propietario).zip:
Index(['directorio', 'secuencia_p', 'secuencia_encuesta', 'p3088', 'p3089',
       'p3090', 'p2989', 'p3091', 'sueldos', 'prestaciones',
       'remuneracion_total', 'clase_te', 'cod_depto', 'area', 'f_exp'],
      dtype='object')
Columns name for E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip:
Index(['directorio', 'secuencia_p', 'secuencia_encuesta', 'p3053', 'p3095',
       'p3096', 'p3097', 'p3098', 'p3054', 'p3055', 'p469', 'clase_te',
       'cod_depto', 'area', 'f_exp'],
      dtype='object')
Columns name for E:\pobreza_2021\data\emicron\2021\Modulo_TIC.zip:
Index(['directorio', 'secuencia_p', 'secuencia_encuesta', 'p4001', 'p1087',
       'p1088', 'p977', 'p976', 'p978', 'p979', 'p994', 'p2532', 'p1559',
       'p2524', 'p1093', 'p2528', 'p1095', 'p980', 'p1006_1', 'p1006_2',
       'p1006_3', 'p1006_4', 'p1006_5', 'p1006_6', 'p1006_7', 'p1006_8',
       'p1006_9', 'p1006_10', 'p1006_11', 'p1006_12', 'p1006_13', 'clase_te',
       'cod_depto', 'area', 'f_exp'],
      dtype='object')
Columns name for E:\pobreza_2021\data\emicron\2021\Modulo_ventas_ingresos.zip:
Index(['directorio', 'secuencia_p', 'secuencia_encuesta', 'p3057', 'p3058',
       'p3059', 'p3060', 'p3061', 'p3062', 'p4002', 'p3063', 'p3064', 'p3065',
       'p3066', 'p3067', 'p3092', 'p3093', 'p4036', 'p4005', 'p4006', 'p4007',
       'p4008', 'p4009', 'p4010', 'p4011', 'p4012', 'p4013', 'p4014', 'p4015',
       'p4016', 'p4017', 'p4018', 'p4037', 'p3068_ene', 'p3068_feb',
       'p3068_mar', 'p3068_abr', 'p3068_may', 'p3068_jun', 'p3068_jul',
       'p3068_ago', 'p3068_sep', 'p3068_oct', 'p3068_nov', 'p3068_dic',
       'p3068_tod', 'p3068_nin', 'p4019', 'p4020', 'p4021', 'p4022', 'p4023',
       'p4024', 'p4025', 'p4026', 'p4027', 'p4028', 'p4029', 'p4030', 'p4031',
       'p4032', 'p4038', 'p3072', 'ventas_mes_anterior',
       'ventas_mes_anio_anterior', 'ventas_anio_anterior', 'valor_agregado',
       'ingreso_mixto', 'clase_te', 'cod_depto', 'area', 'f_exp'],
      dtype='object')

# Join all dataframe with a base dataframe selected

In [6]:
# make a list with dictionary keys or dataframe names (exclude one of location)
zip_file_names = list(csv_dict.keys())
zip_file_names.pop(6)
zip_file_names

['E:\\pobreza_2021\\data\\emicron\\2021\\Factor_expansion_departamental.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_caracteristicas_del_micronegocio.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_costos_gastos_y_activos.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_emprendimiento.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_identificacion.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_personal_ocupado_(propietario).zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_TIC.zip',
 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_ventas_ingresos.zip']

In [7]:
# choose the base dataframe and iterate over the list to merge the other dataframes

base_df = csv_dict[zip_file_names[0]]

# jooin all the other dataframes to the base dataframe
for i in range(1, len(zip_file_names)):
    zip_file_name = zip_file_names[i]
    df = csv_dict[zip_file_name]
    df.drop(columns = ['f_exp', 'clase_te', 'cod_depto', 'area'], inplace = True)
    base_df = pd.merge(base_df, df, on = ['directorio', 'secuencia_p', 'secuencia_encuesta'], how = 'left', indicator='indicator_'+zip_file_name)
base_df.shape

(77156, 181)

In [8]:
#merge the remaining dataframe 

zip_file_name = 'E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_sitio_ubicacion.zip'
df = csv_dict[zip_file_name]
base_df = pd.merge(base_df, df, on = ['directorio', 'secuencia_p', 'secuencia_encuesta'], how = 'left', indicator='indicator_'+zip_file_name)

In [9]:
base_df.columns.tolist()

['directorio',
 'secuencia_encuesta',
 'secuencia_p',
 'fex_micro_dpto',
 'p1633',
 'p986',
 'p640',
 'p4000',
 'p1055',
 'p1056',
 'p661',
 'p1057',
 'p4004',
 'p2991',
 'p2992',
 'p2993',
 'indicator_E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_caracteristicas_del_micronegocio.zip',
 'p3056_a',
 'p3056_b',
 'p3056_c',
 'p3056_d',
 'p3056_e',
 'p3057_a',
 'p3057_b',
 'p3057_c',
 'p3057_d',
 'p3057_e',
 'p3017_a',
 'p3017_b',
 'p3017_c',
 'p3017_d',
 'p3017_e',
 'p3017_f',
 'p3017_g',
 'p3017_h',
 'p3017_k',
 'p3017_i',
 'p3017_j',
 'p3017_l',
 'p3018_1',
 'p3018_2',
 'p3018_3',
 'p3018_4',
 'p3018_5',
 'p3018_6',
 'p3018_7',
 'p3018_a',
 'p3018_b',
 'p3018_c',
 'p3018_d',
 'p3018_e',
 'p3018_f',
 'p3019',
 'costos_mes_anterior',
 'costos_anio_anterior',
 'gastos_mes',
 'consumo_intermedio',
 'indicator_E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_costos_gastos_y_activos.zip',
 'p3050',
 'p3051',
 'p639',
 'p3052',
 'indicator_E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_emprendimiento.zip',
 'p35',
 'p241',
 'mes_ref',
 'p3031',
 'p3032_1',
 'p3032_2',
 'p3032_3',
 'p3033',
 'p3034',
 'p3035',
 'p3000',
 'grupos4',
 'grupos12',
 'indicator_E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_identificacion.zip',
 'p3088',
 'p3089',
 'p3090',
 'p2989',
 'p3091',
 'sueldos',
 'prestaciones',
 'remuneracion_total',
 'indicator_E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_personal_ocupado_(propietario).zip',
 'p4001',
 'p1087',
 'p1088',
 'p977',
 'p976',
 'p978',
 'p979',
 'p994',
 'p2532',
 'p1559',
 'p2524',
 'p1093',
 'p2528',
 'p1095',
 'p980',
 'p1006_1',
 'p1006_2',
 'p1006_3',
 'p1006_4',
 'p1006_5',
 'p1006_6',
 'p1006_7',
 'p1006_8',
 'p1006_9',
 'p1006_10',
 'p1006_11',
 'p1006_12',
 'p1006_13',
 'indicator_E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_TIC.zip',
 'p3057',
 'p3058',
 'p3059',
 'p3060',
 'p3061',
 'p3062',
 'p4002',
 'p3063',
 'p3064',
 'p3065',
 'p3066',
 'p3067',
 'p3092',
 'p3093',
 'p4036',
 'p4005',
 'p4006',
 'p4007',
 'p4008',
 'p4009',
 'p4010',
 'p4011',
 'p4012',
 'p4013',
 'p4014',
 'p4015',
 'p4016',
 'p4017',
 'p4018',
 'p4037',
 'p3068_ene',
 'p3068_feb',
 'p3068_mar',
 'p3068_abr',
 'p3068_may',
 'p3068_jun',
 'p3068_jul',
 'p3068_ago',
 'p3068_sep',
 'p3068_oct',
 'p3068_nov',
 'p3068_dic',
 'p3068_tod',
 'p3068_nin',
 'p4019',
 'p4020',
 'p4021',
 'p4022',
 'p4023',
 'p4024',
 'p4025',
 'p4026',
 'p4027',
 'p4028',
 'p4029',
 'p4030',
 'p4031',
 'p4032',
 'p4038',
 'p3072',
 'ventas_mes_anterior',
 'ventas_mes_anio_anterior',
 'ventas_anio_anterior',
 'valor_agregado',
 'ingreso_mixto',
 'indicator_E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_ventas_ingresos.zip',
 'p3053',
 'p3095',
 'p3096',
 'p3097',
 'p3098',
 'p3054',
 'p3055',
 'p469',
 'clase_te',
 'cod_depto',
 'area',
 'f_exp',
 'indicator_E:\\pobreza_2021\\data\\emicron\\2021\\Modulo_sitio_ubicacion.zip']

In [9]:
## verify the merge process

for vars in zip_file_names:
    
    print(base_df['indicator_'+zip_file_name].value_counts())

both          77156
left_only         0
right_only        0
Name: indicator_E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip, dtype: int64
both          77156
left_only         0
right_only        0
Name: indicator_E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip, dtype: int64
both          77156
left_only         0
right_only        0
Name: indicator_E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip, dtype: int64
both          77156
left_only         0
right_only        0
Name: indicator_E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip, dtype: int64
both          77156
left_only         0
right_only        0
Name: indicator_E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip, dtype: int64
both          77156
left_only         0
right_only        0
Name: indicator_E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip, dtype: int64
both          77156
left_only         0
right_only        0
Name: indicator_E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip, dtype: int64
both          77156
left_only         0
right_only        0
Name: indicator_E:\pobreza_2021\data\emicron\2021\Modulo_sitio_ubicacion.zip, dtype: int64

# Data manipulation to create some variables

In [10]:
np.set_printoptions(precision=4, suppress=True)
pd.options.display.float_format = '{:.4f}'.format

In [ ]:
# verify the whole number of observations (contrast with DANE information)
4032623.0461+1747999.6277

5780622.6738

In [39]:
## make a function to create proportions of the variable of interest
def take_prop(var):
    df = base_df.groupby(var,group_keys=False)['f_exp'].sum().reset_index()
    df['proportions'] = ((df['f_exp']/df['f_exp'].sum())*100)
    df = df.sort_values(by = "proportions", ascending = False)
    return df

In [40]:
# take a look

dpto_df = take_prop("cod_depto")
area_df = take_prop("area")
area_df.head()

      area       f_exp  proportions
2  11.0000 569529.2760      23.4848
0   5.0000 369472.8437      15.2354
1   8.0000 304603.5466      12.5605
22 76.0000 256311.6357      10.5691
19 68.0000 162484.4649       6.7001